### ISSUE TITLE
Upgrade SDK and Plugin to 2.1 Compatible

### ISSUE THREAD

**Issue by lovingmage** [lovingmage/SGXBcftools#11]
Please follow the Engineering Rule, section Git to upgrade the whole SGX project, which should satisfy the following requirements:

- Should upgrade plugin to SGX SDK 2.1 compatible version.
- Should update protected file system.

**Comment by Leo-ATP** [comment]
* Upgrade plugin to SGX SDK 2.1 compatible version.
* Update protected file system.
